### ISSUE TITLE
sb_vision.cvcapture.ImageCaptureError: cvcapture() failed

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/sb-vision#4]
# Steps taken

Run robotd on my laptop, which has a built-in webcam.

sb-version: 672207d86b3d6f00824ffb428762f49d8c352aa4 (master at time of writing)
robotd version: 9e15ccf84b82a2ec5063bb7fe71038dfd4796579 (master at time of writing)

# Expected results

robotd starts running and detects the presence of a webcam, and/or reports that this model of webcam is unsupported.

# Actual results

    $ robotd --root-dir /tmp/robotd
    Listening on: /tmp/robotd/game/state
    Detected new Camera: /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3/1-1.3:1.0/video4linux/video0 (video0)
    Listening on: /tmp/robotd/camera/video0
    HIGHGUI ERROR: V4L/V4L2: VIDIOC_S_CROP
    HIGHGUI ERROR: V4L/V4L2: VIDIOC_S_CROP
    HIGHGUI ERROR: V4L: setting property #6 is not supported
    Incorrect width set on cap: 640.000000
    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/nix/store/1cmq5nwr6gp51jp1bsq647sqcb3dc3zy-python3-3.5.3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/nix/store/1cmq5nwr6gp51jp1bsq647sqcb3dc3zy-python3-3.5.3/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/nix/store/jm0vlr46l5sk5qxmfjlhnybmz4kxan69-robotd-1.0/lib/python3.5/site-packages/robotd/devices.py", line 232, in _vision_thread
        latest = [x.__dict__ for x in self.vision.snapshot()]
      File "/nix/store/56lxp1fcka72l2n7jcihbydm7npxl0l7-python3.5-sb-vision-1.0/lib/python3.5/site-packages/sb_vision/vision.py", line 162, in snapshot
        return self.process_image(self.capture_image())
      File "/nix/store/56lxp1fcka72l2n7jcihbydm7npxl0l7-python3.5-sb-vision-1.0/lib/python3.5/site-packages/sb_vision/vision.py", line 119, in capture_image
        return self.camera.capture_image()
      File "/nix/store/56lxp1fcka72l2n7jcihbydm7npxl0l7-python3.5-sb-vision-1.0/lib/python3.5/site-packages/sb_vision/camera.py", line 51, in capture_image
        image_bytes = self.camera.capture(*self.cam_image_size)
      File "/nix/store/56lxp1fcka72l2n7jcihbydm7npxl0l7-python3.5-sb-vision-1.0/lib/python3.5/site-packages/sb_vision/cvcapture.py", line 64, in capture
        raise ImageCaptureError()
    sb_vision.cvcapture.ImageCaptureError: cvcapture() failed

---

I have two questions here:

1. Why does robotd attempt to capture a photo before a user program has connected to a `/var/robotd/camera/XXX` socket?
2. Does this exception result from the webcam model and/or resolution being unsupported? If so, we should probably catch the exception and display a nicer log message. If not, it's probably a bug.

I appreciate that a single traceback is unlikely to be enough information to resolve this problem, so please let me know what else I provide to help with this.

**Comment by PeterJCLaw** [comment]
Hi @kierdavis,

> 1. Why does robotd attempt to capture a photo before a user program has connected to a /var/robotd/camera/XXX socket?

The current (I think) architecture of the vision system is that the camera is always taking and analysing images. I _think_ (though I'd love to hear from the original developers - @Adimote?) that this is so that there are always results ready and available when the user code requests them from `robot-api`.

This was something that I found to be confounding to the issues I hit with getting the C270s to work at the Smallpeice summer school, so was something I removed in favour of a more reactive approach (i.e: user requests data -> take and analyse photo -> return data), though that obviously ends up blocking the client's main thread for a lot longer. I can't remember whether this change got merged though.

I think that the reactive approach is better in general as it allows the client to cope with things like motion blur if they're found to be an issue, _as well as_ implementing the full dynamic approach if they want to (by spinning up their own thread to loop over grabbing image data). I'm not sure how well this model fits with the design of `robotd` though.

> 2. Does this exception result from the webcam model and/or resolution being unsupported? If so, we should probably catch the exception and display a nicer log message. If not, it's probably a bug.

The interesting line here is
```
Incorrect width set on cap: 640.000000
```
Which indicates that we're trying to use a resolution that the camera doesn't support. I'm not sure why this then raises the exception that it does, and I agree we should ideally be better at reporting the underlying error.

Unfortunately since we're routing through opencv for the actual vision support, I'm not sure how much control we have over these things -- it's quite possible that all we get back from opencv is a generic error code that something went wrong and they expect a developer to be able to look at the printed output to fix the issue. I do know that if we bind directly to V4L this is the sort of thing that we _can_ detect and correct for (which is how `pykoki` does it for example).

This would need some investigation into the C parts of `cvcapture` & the related opencv API to determine how much we can actually detect programatically.

**Comment by PeterJCLaw** [comment]
Separately, it looks like the error lines
```
HIGHGUI ERROR: V4L/V4L2: VIDIOC_S_CROP
```
may be caused by not having the v4l development headers around when one compiles opencv. I wonder whether we have something missing in our dependency listing?

**Comment by kierdavis** [comment]
Thanks for the analysis, this gives me a couple of leads to investigate further with this issue.

> Separately, it looks like the error lines <snip> may be caused by not having the v4l development headers around when one compiles opencv. I wonder whether we have something missing in our dependency listing?

It's more likely that it's something missing in the way I'm compiling opencv (well, the way Nix compiles opencv). I think this is outside the scope of our dependency specification since we assume opencv is already built, unless there's a way to specify which opencv features/modules are required.

**Comment by kierdavis** [comment]
(triage) I don't think I'm likely to personally use sb-vision again in the near future, and it seems I'm the only one who was experiencing this problem. If it resurfaces I'll reopen.
